name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "website/**/*"
      - ".github/workflows/deploy_website.yml"

jobs:
  deploy:
    name: Website
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Website
        run: pnpm turbo run build --filter=website

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: typethings
          entrypoint: server/entry.mjs
          root: dist
